version: '3.7'
services:
    postgres:
        image: postgres:10.5
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=go_crud
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - "5432:5432"
        volumes: 
          - ./docker/data/pg:/var/lib/postgresql/data
          - ./docker/sql/init.sql:/docker-entrypoint-initdb.d/init.sql